import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from './components/Provider'
import ToastComponent from './components/ToastComponent'
import TanstackProvider from './components/TanstackProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <TanstackProvider>
            <main>
              {children}
              <ToastComponent />
            </main>
          </TanstackProvider>
        </Provider>
      </body>
    </html >
  )
}
